### ISSUE TITLE
Kashyyyk Czerka Landing Port - Crates need to be opened twice to get their loot

### ISSUE THREAD

**Issue by muitafruita** [KOTORCommunityPatches/K1_Community_Patch#626] opened 2022-06-20 12:52 UTC
You need to open the two crates by the entrance of the Czerka office twice in order to get their loot. I remember this bug from when I would check every footlocker twice in my first runs.

**Comment by DarthParametric** [comment] 2022-06-20 13:24
It's not a bug _per se_, just an artefact of the method they used to generate random loot. It seems they encountered performance issues when using OnHeartbeat scripts to do it (which Obsidian resolved in TSL by creating a new one-shot OnHeartbeat function). Instead, they occasionally use an OnOpen script (`k_plc_tresmilmid` in this case). The drawback being that it doesn't fire until the player tries to loot it once. A similar sort of issue can be seen in  #172, although interestingly in that case they _do_ use OnHeartbeats but still require looting twice. My guess is due to some sort of deliberate performance-saving measure.

In any event, the most expedient solution would be to push any such examples to the module's OnEnter. But it is not exactly a high priority.

**Closed** 2022-08-09 07:43 UTC
Labels: Low Priority, Module: Kashyyyk, Type: Scripting, Type: Template
