### ISSUE TITLE
Sandral-Matale issues

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#591] opened 2022-06-10 02:15 UTC
One of Alan Matale's lines is played while pointing the camera at Nurik Sandral, during the dialogue branch in which the player dissuades Romeo from running away with Juliet.

Additionally, the evolution of that branch of dialogue doesn't make sense RPG-wise. After the player says "Why don't you just shoot each other and get it over with" and then backs down and says "If you fight, you'll all be killed," then the player is forced to dissuade Romeo from running away with Juliet (all 3 options aim at this).

**Comment by DarthParametric** [comment] 2022-06-10 04:36
The first issue is a duplicate of #158.

The second issue is outside the scope of the mod.

**Closed by DarthParametric** 2022-06-10 04:36 UTC
Labels: Duplicate
