### ISSUE TITLE
Taris Upper City South - Animation pause on first dialogue line with Zelka 

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#188] opened 2019-06-25 11:18 UTC
The tar02_zelka021.dlg file contains a script (k_ptar_labpause) that freezes the animation for the first Player reply.

In my opinion it should be simply removed.

**Comment by DarthParametric** [comment] 2019-06-25 11:22
It's just a pause in the conversation. That doesn't cause an animation freeze, that is caused by the LISTENER tag, or lack thereof.

**Comment by Salk73** [comment] 2019-06-25 11:54
You are right.

The issue is solved by swapping "tar02_labdoor" with PLAYER in the LISTENER field. Still, it is a bug.

**Comment by DarthParametric** [comment] 2019-06-26 05:07
It was probably already fixed in 0583b5b2b983b0291853e9db0aba43e10fb70ad3 . What's the specific entry number in the DLG?

**Comment by DarthParametric** [comment] 2019-06-27 05:35
In the absence of anything to the contrary, I am going to assume this is Entry 76 `What are you doing? Don't go in there! That door is for employees only!`. I'll add it to the existing fixes for that DLG.

**Closed** 2019-06-27 05:37 UTC
Labels: Minor Issue, Module: Taris, Type: Conversation
