### ISSUE TITLE
Manaan Ahto East - Couple of issues with arrest cutscene

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#371] opened 2019-12-05 12:06 UTC
The cutscene that starts when the Player leaves the Sith Embassy on Manaan is somewhat awkward.

First of all the party is not spawned properly, with the Player in the rear. On top of that, the Selkath officer is not facing the party when the cutscene starts and it is jarring to see this being corrected as soon as he starts speaking.

This video shows this is a vanilla game issue: https://youtu.be/nBI2zuqTeCU?t=664

I fixed this locally.

And now the sequence looks like this: https://youtu.be/OaE4rkQdcJs

To do that, I have removed the fade from E0 in the man26_selarrest.dlg file and added some code to k_pman_temp04.

```
#include "cp_inc_k1"

void PartyRegroup(object oPC, object oNPC0, object oNPC1, object oNPC2, location lLoc0, location lLoc1, location lLoc2);

void PartyRegroup(object oPC, object oNPC0, object oNPC1, object oNPC2, location lLoc0, location lLoc1, location lLoc2) {

  CP_PartyJump(oPC, lLoc0);
  if (GetPartyMemberCount() == 3) {
    if (oPC == oNPC0) {
      CP_PartyJump(oNPC1, lLoc1);
      CP_PartyJump(oNPC2, lLoc2);
    }
    else if (oPC == oNPC1) {
      CP_PartyJump(oNPC0, lLoc1);
      CP_PartyJump(oNPC2, lLoc2);
    }
    else {
      CP_PartyJump(oNPC0, lLoc1);
      CP_PartyJump(oNPC1, lLoc2);
    }
  }
  else if (GetPartyMemberCount() == 2) {
    if (oPC == oNPC0) {
      CP_PartyJump(oNPC1, lLoc1);
    }
    else {
      CP_PartyJump(oNPC0, lLoc1);
    }
  }
} 

void main() {
  object oHangarSith = GetItemPossessedBy(GetFirstPC(), "w_sithkey2");
  object oSithPass = GetItemPossessedBy(GetFirstPC(), "W_SITHKEY");
  object oPC = GetFirstPC();
  object oNPC0 = GetPartyMemberByIndex(0);
  object oNPC1 = GetPartyMemberByIndex(1);
  object oNPC2 = GetPartyMemberByIndex(2);

  vector vVec0 = Vector(44.0, 11.2, 57.5);
  vector vVec1 = Vector(43.0, 13.2, 57.5);
  vector vVec2 = Vector(45.0, 12.7, 57.5);

  location lLoc0 = Location(vVec0, 270.0);
  location lLoc1 = Location(vVec1, 270.0);
  location lLoc2 = Location(vVec2, 270.0);

  ActionPauseConversation();
  DelayCommand(0.5, ActionResumeConversation());
  DelayCommand(0.2, PartyRegroup(oPC, oNPC0, oNPC1, oNPC2, lLoc0, lLoc1, lLoc2));

  SetGlobalFadeOut(0.0, 0.5, 0.0, 0.0, 0.0);
  SetGlobalFadeIn(0.5, 1.5, 0.0, 0.0, 0.0);

  SetGlobalBoolean("MAN_TEMP2", 1);
```

**Comment by DarthParametric** [comment] 2019-12-05 12:17
Duplicate of #139.

**Closed by DarthParametric** 2019-12-05 12:17 UTC
