### ISSUE TITLE
Installer Issue

### ISSUE THREAD

**Issue by Hakubi-Washu** [KOTORCommunityPatches/K1_Community_Patch#577] opened 2022-03-15 17:50 UTC
Downloaded the K1_Community_Patch_v1.9.1.zip from Deadlystream, extracted all and run the Install.exe. Using the correct swkotor folder, however every time I run it I encounter the following error:

[Error] 	Error loading CResRef field, string is too long! (GFF-8)

Happens when it reaches:

[Install] 	GFF File k_hhkd_dialog.dlg does exists: E:\Steam\steamapps\common\swkotor\override\.

**Comment by DarthParametric** [comment] 2022-05-05 05:58
Late reply, and I'm going to assume at this point you have sought help elsewhere and/or already resolved this, so I am going to close this issue. For future reference, this is commonly caused by running the installer from too deep within a folder structure. For example, from the Desktop if that is in its default location. Always run TSLPatcher as close as possible to the root of a drive.

**Closed by DarthParametric** 2022-05-05 05:58 UTC
