### ISSUE TITLE
Xor: can't talk to him after beating him

### ISSUE THREAD

**Issue by Myrthian** [KOTORCommunityPatches/K1_Community_Patch#429] opened 2020-09-06 10:50 UTC
- Triggered the 1st Xor cutscene and got the quest
- Triggered the 2nd cutscene and fought him, but now I'm unable to talk to him

1.8.1
Save game once I defeated him: https://www.file-upload.com/ae97pf87d9fi

**Comment by DarthParametric** [comment] 2020-09-06 11:13
This is a duplicate of #8. The issue has never been resolved because it cannot be reliably reproduced.

**Closed by DarthParametric** 2020-09-06 11:13 UTC
Labels: Duplicate

**Comment by JCarter426** [comment] 2020-09-06 11:16
If you have a save file that can reliably reproduce it though, we'd like to see it.
