### ISSUE TITLE
Upper City Cantina - Waiter gets stuck if the PC stands between placeables

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#593] opened 2022-06-10 23:39 UTC
Due to the game's terrible NPC pathing, the waiter eventually gets stuck in a looping path (which makes him teleport) if the PC stands between the two tables in the room, as well as between Gana's table and the closest seat (especially if they bring a companion, like Carth).

His walking route could be tweaked so that he makes an L through the front and the other side of the room, where there's more room for him to maneuver and where the PC is less likely to interrupt his route.

**Comment by DarthParametric** [comment] 2022-06-11 08:38
Appears to be a duplicate of #232.

**Closed by DarthParametric** 2022-06-11 08:38 UTC
