### ISSUE TITLE
Escape from Xor to Ebon Hawk

### ISSUE THREAD

**Issue by WildKarrde1138** [KOTORCommunityPatches/K1_Community_Patch#704] opened 2023-10-15 22:12 UTC
It is possible to escape the fight with Xor by running into the Ebon Hawk.  This happened on accident on Korriban during my last playthrough when the fight got too close to the Ebon Hawk's ramp and I stumbled into the area transition trigger.  Xor and his goons were still there when I went back outside, and I was able to continue the fight as if nothing had happened, so nothing was seriously broken.  However, I do not know if traveling to another planet at that point would have broken anything.  While I suppose escaping into the ship is arguably a realistic option, I suspect this was not intended behavior.

**Comment by DarthParametric** [comment] 2023-10-16 06:49
Yes, I did this myself accidentally at least once when testing the Xor fixes on Manaan. I'm not sure if it is possible to resolve. Transition zones are triggers, but they work automatically, not based on scripts. The only practical option I can see would be to extend the hangar outwards and push the Hawk back 5m or so in order to create enough space. Something that radical is really beyond the scope of K1CP though.

Kashyyyk is probably the same. Korriban is similar, although there at least we do have a little more wiggle room to push the fight a bit further away by tweaking the waypoint positions. Tatooine should have plenty of room, so those waypoints could also be pushed back further.

**Comment by DarthParametric** [comment] 2023-11-18 05:52
There's not really enough room for that, at least on Manaan. And that's really the main problem. The other planets have a bit more room to shuffle positions around, although Kashyyyk is probably the next most limited.

We can't temporarily destroy the transition, because there is no scriptable command for spawning a trigger object. However, we could potentially temporarily spawn a placeable walkmesh (e.g. PLC_Blockage) over the top of the trigger that would block anyone from entering it. It's a pretty hacky approach, but it could work. The transition trigger zone would need to be modified to be smaller, since on Manaan Xor spawns right on the edge of it.

**Comment by DarthParametric** [comment] 2023-11-20 13:27
So I have done some preliminary testing of the solution I proposed above:

https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/46890653/b6c4d940-5c1a-475d-9bce-cf26b1bd25f8

Extended version: https://www.youtube.com/watch?v=uB1-6k7TfYY

It still needs a little tweaking on the regular (non-combat) transition side of things in order to match the vanilla fade-out as closely as possible. But it seems to work fine mechanically. I'll add this to all the applicable modules for the first v1.10 beta test and see if any problems crop up.

**Comment by DarthParametric** [comment] 2023-11-21 09:10
Test version: [K1CP_Xor_Ebon_Hawk_Transition_Replacement_BETA.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/13424099/K1CP_Xor_Ebon_Hawk_Transition_Replacement_BETA.zip)

**Comment by DarthParametric** [comment] 2023-11-23 08:10
Initial testing suggests it isn't entirely foolproof. If you save in combat with Xor and reload, if you are close enough you can manage to get to the trigger and enter the Hawk before the AI ticks over to combat re-engaging. Maybe it needs an additional check for hostile creatures within some radius (10m?) of the trigger.

**Comment by DarthParametric** [comment] 2023-12-04 08:23
Did the second encounter with Xor on Tatooine during the 1.10.0 beta test and it worked as intended. Didn't have any issues with normal transitions on Manaan/Kashyyyk/Tatooine. Just landed on Korriban, so yet to test there.

**Comment by DarthParametric** [comment] 2023-12-05 09:13
OK with some minor adjustments to the Dreshdae trigger, I think this is good to go for inclusion.

**Closed** 2023-12-06 06:21 UTC
Labels: Minor Issue, Module: Tatooine, Module: Kashyyyk, Module: Manaan, Module: Korriban, Type: Scripting, Type: Module
