### ISSUE TITLE
Korriban Tomb of Ajunta Pall - Blowing up pillar scene

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#164] opened 2019-05-20 17:12 UTC
After blowing up the pillar on the bridge, in the following cutscene of the droids powering up some of the UI is still visible. Notably the pause/solo/stealth section in the left hand corner.  I don't think I have seen this occur before.

**Comment by JCarter426** [comment] 2019-05-28 04:21
I wasn't able to reproduce that AI-breaking bug that was reported elsewhere, but I did experience GUI issues, and it was weirder than just being visible in the cutscene. I was still sort of semi-in control of my player while the cutscene was going.

I suspect all issues can be resolved with some massaging of the cutscene trigger. Adding a `NoClicksFor()` and/or changing it from OnInvDisturbed to OnClosed may sort it.

Also, I noticed it's possible to interact with the other pillar - the one blocking the droids - even though you can't do anything with it. Should be set to not interactable to remove the distraction.

**Comment by DarthParametric** [comment] 2019-07-10 12:00
Here's something interesting. Not sure if it is related or not, but the party member AI gets switched off on the opening node of the cutscene:
```
#include "k_inc_generic"

void AIToggle(int nIndex, int nState) {
	SetLocalBoolean(OBJECT_SELF, nIndex, nState);
}

void main() {
	
	object oArea = GetArea(OBJECT_SELF);
	object oTherObel = GetObjectByTag("kor37_therangen", 0);
	object oPM0 = GetPartyMemberByIndex(0);
	object oPM1 = GetPartyMemberByIndex(1);
	object oPM2 = GetPartyMemberByIndex(2);
	object oPartyWP = GetObjectByTag("k37_way_player1", 0);
	
	MusicBackgroundStop(oArea);
	DelayCommand(0.1, MusicBattlePlay(oArea));
	SetPlotFlag(oTherObel, 0);
	
	ActionPauseConversation();
	
	AssignCommand(oPM0, ActionMoveToObject(oPartyWP, TRUE));
	
	if (((!GetSoloMode()) && GetIsObjectValid(oPM1)))
		{
			AssignCommand(oPM1, AIToggle(SW_FLAG_AI_OFF, TRUE));
			AssignCommand(oPM1, ClearAllActions());
			AssignCommand(oPM1, ActionMoveToObject(oPartyWP, TRUE));
		}
	
	if (((!GetSoloMode()) && GetIsObjectValid(oPM2)))
		{
			AssignCommand(oPM2, AIToggle(SW_FLAG_AI_OFF, TRUE));
			AssignCommand(oPM2, ClearAllActions());
			AssignCommand(oPM2, ActionMoveToObject(oPartyWP, TRUE));
		}
	
	ActionWait(2.0);
	ActionResumeConversation();
}
```

**Comment by JCarter426** [comment] 2019-07-11 01:40
Interesting. That could explain why the party AI bugs out, even if we couldn't reproduce the bug. The cutscene may have been broken in some way so the script to turn the AI back on didn't fire.

**Comment by DarthParametric** [comment] 2019-07-12 06:55
So I switched the pillar placeable's script from OnDisturbed to OnClosed, and made a few script tweaks to add `NoClicksFor`. I also made the DLG unskippable just for good measure. No noticeable issues, although I never saw the AI bug previously either. I didn't spot any UI issues this time around, but I'll have to check it again to be sure. 

I also made the other pillar placeable non-interactive. Not sure why they didn't just make that part of the level.

**Comment by DarthParametric** [comment] 2019-07-12 10:22
Revised sequence:

https://youtu.be/5VUDYwAOuSY

For some reason it seems that the PC tries to turn around and face the explosion mid-way through running away. I'm not sure why. There doesn't seem to be anything special going on in the script that triggers the effect and the Speaker/Listener tags on that dialogue node are empty. One possible way around it would be to delay the opening node another second so that the PC is off-screen by the time it triggers. It's almost at that point anyway, since I have lengthened it a couple of times to squeeze in extra party wrangling elements.

**Comment by DarthParametric** [comment] 2019-07-12 13:39
Tweaked to include the change mentioned above:

https://youtu.be/-mIx_ilB920

I think the only thing left might be tweaking the camera angle on the third droid activation. The framing is a little weird.

**Closed** 2019-07-12 16:00 UTC
Labels: Minor Issue, Module: Korriban, Type: Scripting, Type: Template
