### ISSUE TITLE
Kashyyyk - Generic Wookiees have an incorrect mouth texture and males have a missing tongue

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#295] opened 2019-10-05 08:29 UTC
- Reported by @Salk73 at October 05, 2019

> ...the wookie male textures seem to have a big problem with the inside of the mouths. Meaning that it is just missing. This doesn't seem to happen with the female and with Chuundar, for instance, just the generic male textures.

Apparently all the generic male Wookiee hi-poly textures [except Chuundar/`N_WookieM06`] are missing the mouth texture/details, as seen below - 
![N_WookieM06xN_WookieM01_Comp](https://user-images.githubusercontent.com/50026566/66252174-5fc4ab80-e782-11e9-9b97-d26120df312a.jpg)
The left one is Chuundar's `N_WookieM06` and the right one is one of the generics `N_WookieM01`.

A fix that I am offering would be by patching the mouth texture from Chuundar's to the relevant male Wookiee's -
![N_WookieM01_Fixed_Mouth](https://user-images.githubusercontent.com/50026566/66252245-35bfb900-e783-11e9-92a0-fcc303de0cba.jpg)

Hence the in-game result -
![K1_Male_Wookie_Mouth_Fix_Preview](https://user-images.githubusercontent.com/50026566/66252241-2d677e00-e783-11e9-823d-d262e9b09cf8.jpg)

Attached is the archived TPCs and TGAs of the aforementioned fix -
[[K1]_Male_Wookiee_Mouth_Fix_[BETA].zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3692998/K1._Male_Wookiee_Mouth_Fix_.BETA.zip)

**Comment by DarthParametric** [comment] 2019-10-05 08:33
Looks like that's just a duplicate of the texture patch on the upper left. Might be better to adjust the UVs.

**Comment by ebmar** [comment] 2019-10-05 08:38
> Might be better to adjust the UVs.

Yeah, that sounds more proper. Actually the patch result is not really great, particularly with the tongue area, and I do feel further improvement would be needed. I'm interesting to see how it looks by adjusting the UVs!

**Comment by DarthParametric** [comment] 2019-10-05 08:50
The tongue should be in that section next to the face, so nothing should have changed with your texture edit.

**Comment by DarthParametric** [comment] 2019-10-05 09:04
Here @ebmar, try this and see how it goes. 

[n_wookiem_Fixed_UVs.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3693038/n_wookiem_Fixed_UVs.zip)

**Comment by ebmar** [comment] 2019-10-05 09:12
> ...try this and see how it goes.

That looks awesome! The tongue mesh/shape looks distinctive now. The former looks abstract whilst now is more constructed. How can it achieve that look?

I thought the bottom-flesh-looking-patch in the texture [in `N_WookieM06` for example] works as ceiling of the mouth, or probably the inside of the mouth in overall.

**Comment by DarthParametric** [comment] 2019-10-05 09:22
The regular tongue UVs have two problems. First, they are scaled down to the size of a pixel. Second, they are inside an area covered by the texture's alpha mask, so the whole tongue should be invisible in-game.

![Wookiee_Tongue_UVs](https://user-images.githubusercontent.com/46890653/66252989-687aa900-e7a5-11e9-87cb-ec7ddc74a60c.jpg)

I scaled the UVs up and moved them far enough down that they won't be affected by the alpha mask.

**Comment by ebmar** [comment] 2019-10-05 09:35
Wow. That is amazing. :+1:

> ...they are inside an area covered by the texture's alpha mask, so the whole tongue should be invisible in-game..

Ohh, so that's why.

> ...the rest of the mouthbox now shares the same patch of texture on the top left that the inner lower lip does in the vanilla model.

Good to know! That should provides compatibility with most re/upscaled-textures around now.

**Comment by DarthParametric** [comment] 2019-10-05 09:43
Female Wookiees also have an incorrectly textured mouthbox. Although their tongue looks ok.

**Comment by ebmar** [comment] 2019-10-05 09:45
Yeah, I was about to brought that up [at some point]. The difference between the male [after the fix] and the female is like night and day now, hahah. Well, the same goes with the former male and the current fixed state.

**Comment by DarthParametric** [comment] 2019-10-05 09:52
Try this:

[n_wookief_Fixed_UVs.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3693077/n_wookief_Fixed_UVs.zip)

In both cases, check for any obvious smoothing issues.

**Comment by Salk73** [comment] 2019-10-05 09:56
Excellent job, DP!

As usual... I tested both the new models and it looks very fine here.

**Comment by ebmar** [comment] 2019-10-05 10:09
> ...tested both the new models and it looks very fine here.

Yup, adding what **Salk** had pointed out there with an in-game evidence -
![UVFixed_Male_Female_Wookiees](https://user-images.githubusercontent.com/50026566/66253433-99051780-e792-11e9-81bd-66d99efd948f.jpg)
*Aren't they Wookiees looked happier now?*

**Closed** 2019-10-05 10:12 UTC
Labels: Minor Issue, Type: Asset

**Comment by Salk73** [comment] 2019-10-06 06:44
DP,

I need to report that the new Wookie male model causes Chuundar to have a generic skin.

**Comment by DarthParametric** [comment] 2019-10-06 06:50
Ah, that will be because the default texture the model uses is his, but I was swapping the around to check things and didn't set it back before exporting. I thought he used a unique appearance, but it seems not. I'll push a fix shortly.

**Comment by Salk73** [comment] 2019-10-06 10:50
Confirmed working.

Thanks, DP!

**Comment by RedRob41** [comment] 2025-01-25 04:24
I wish that I'd known about this GitHub site before now. It might have saved me a lot of work. At any rate, I had made similar fixes to my own Wookiee models: "upscaled with touch ups; many UVW edits; texture fix all seams; paint & UVW fix teeth; recreate alpha channel transparency based on final HD texture".

You're welcome to use them if you prefer (once I actually release the of course-hopefully soon).
