### ISSUE TITLE
Ebon Hawk - Dwindling Supplies isn't in quests until you check the container

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#633] opened 2022-06-22 02:53 UTC
All right, take this one with a grain of salt, as I've been having problems with this module, but on my end, when you get the Dwindling Supplies quest from Zaalbar, no new entry appears in active quests until you check the supplies container.

Again, might very well be an issue on my end, and it's a bastard to check what with the previous Calo Nord cutscene and all.

**Comment by DarthParametric** [comment] 2022-06-22 04:41
I see what the issue is. The DLG for Zaalbar initially telling you about the supplies also handles the case of Sasha leaving before you progress/resolve the quest. The exit nodes of both branches use the same script, `k_pebo_zalmove`, to move him back to his original position. It also removes the journal entry, which makes sense for when she leaves. Unfortunately the unintended side-effect is nuking the addition of the journal entry (state 10) that is added on the other branch. 

Easily resolved by assigning R4 its own separate script. Although interestingly the other branch does set the state to 99, which presumably closes it anyway. So perhaps `RemoveJournalQuestEntry` can simply be removed from the script and still used on both exit nodes. I'll need to examine the JRL entries for it.

**Closed** 2022-06-22 06:14 UTC
Labels: Type: Conversation, Minor Issue, Module: Ebon Hawk, Type: Scripting
