### ISSUE TITLE
Zaalbar at the start of Kashyyyk

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#13] opened 2019-01-23 15:27 UTC
Adding Zaalbar to the party right after leaving the Ebon Hawk on Kashyyyk may cause Carth's dialogue to trigger incorrectly.

**Comment by JCarter426** [comment] 2019-01-30 11:04
The dialogue with the party complaining is triggered a bit down the walkway.
I was unable to reproduce this bug when it was originally reported, though.

**Comment by Mako88** [comment] 2019-01-31 14:50
I believe this was reported by a single user, and it may have been an issue with their mod install. If none of us can reproduce it, we can close it, and see if anyone else reports it.

**Comment by DarthParametric** [comment] 2019-01-31 14:54
So was it Carth's dialogue saying to bring Zaalbar that was triggering, despite Zaalbar being in the party?

**Comment by DarthParametric** [comment] 2019-02-01 08:04
I was unable to replicate this bug. 

First attempt:

- Starting from the Ebon Hawk, I exited and chose Carth and Bastila as my party
- I went through the Ithorian's dialogue, then swapped out Bastila for Zaalbar
- Upon reaching the trigger further along the path, I got Zaalbar's dialogue about being exiled
- Carth didn't say anything

Second attempt:

- Starting from the Ebon Hawk, I exited with only the player
- I went through the Ithorian's dialogue, then added Carth and Zaalbar to the party
- Upon reaching the trigger further along the path, I got Zaalbar's dialogue about being exiled
- Carth didn't say anything

**Comment by JCarter426** [comment] 2019-02-01 11:08
Could not reproduce. Closed until the situation changes, if ever.

**Closed by JCarter426** 2019-02-01 11:08 UTC
Labels: Bug, Could Not Reproduce, Module: Kashyyyk
